# Generated by Django 4.2.4 on 2023-08-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('body', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(upload_to='', verbose_name='изображение')),
                ('data_create', models.DateField(verbose_name='дата создания')),
                ('sign_publication', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
    ]
