# Generated by Django 4.2.4 on 2023-08-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('body', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(upload_to='', verbose_name='изображение')),
                ('data_create', models.DateField(verbose_name='дата создания')),
                ('sign_publication', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
